<?php

/**
 * @file
 * Primary module hooks for Neo | Tooltip module.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\neo_tooltip\ElementPreRender;
use Drupal\neo_tooltip\ElementProcess;

/**
 * Implements hook_js_settings_alter().
 */
function neo_tooltip_js_settings_alter(array &$settings, AttachedAssetsInterface $assets) {
  /** @var \Drupal\neo_tooltip\Settings\Settings $config */
  $config = \Drupal::service('neo_tooltip.settings')->getActive();
  $settings['neoTooltip'] = array_diff_key($config->getValues(), ['color' => '']);
  $settings['neoTooltip']['dir'] = \Drupal::moduleHandler()->getModule('neo_tooltip')->getPath();
}

/**
 * Implements hook_preprocess_form_element().
 */
function neo_tooltip_preprocess_form_element(&$variables) {
  if (!empty($variables['element']['#title']) && is_array($variables['element']['#title']) && !empty($variables['element']['#title']['#tooltip'])) {
    // @todo review after automatic tooltipping was added.
    $variables['attributes']['class'][] = 'use-neo-tooltip';
    $variables['attributes']['data-tippy-content'] = $variables['element']['#title']['#tooltip'];
    $variables['#attached']['library'][] = 'neo_tooltip/tooltip';
  }
}

/**
 * Implements hook_element_info_alter().
 */
function neo_tooltip_element_info_alter(array &$info) {
  foreach ($info as &$element) {
    if (isset($element['#process']) && !empty($element['#input'])) {
      $element['#process'][] = [ElementProcess::class, 'processInput'];
    }
  }
  $info['link']['#pre_render'] = array_merge([[ElementPreRender::class, 'link']], $info['link']['#pre_render']);
}

/**
 * Implements hook_library_info_alter().
 */
function neo_tooltip_library_info_alter(&$libraries, $extension) {
  if ($extension == 'core') {
    $libraries['drupal.dropbutton']['js'] = [];
    $libraries['drupal.dropbutton']['css'] = [];
    $libraries['drupal.dropbutton']['dependencies'][] = 'neo_tooltip/dropbutton';
  }
}
